Task 1 ideal weight
gbGiorgi/tasks pull request #11
Opened 2022-03-30 12:11 UTC by gbGiorgi

2022-04-03 12:15 UTC, cyberik-dev requested changes

2022-04-03 12:15 UTC, cyberik-dev commented on Task1/ideal_weight.rb
> +
let's add a call method here and run all other methods inside it

Please read how to use Service Objects in Ruby and try to use them in future tasks. We also use them in rails apps

https://blog.appsignal.com/2020/06/17/using-service-objects-in-ruby-on-rails.html
https://www.honeybadger.io/blog/refactor-ruby-rails-service-object/
https://www.toptal.com/ruby-on-rails/rails-service-objects-tutorial

Service objects are single business actions. You can change the name of your public method if you like. I prefer using call

here is an example
https://paste.ofcode.org/9uJVSsEmVrJZNTTsXs6aLQ

2022-04-03 12:15 UTC, cyberik-dev commented on Task1/ideal_weight.rb
> +    if @height.zero?
you can also print this error if the user passes a negative height

2022-04-03 12:15 UTC, cyberik-dev commented on Task1/ideal_weight.rb
> +  def weight
correct all names in accordance with these recommendations
https://medium.com/selleo/a-subjective-guide-to-naming-stuff-in-ruby-on-rails-classes-b44928b6c49a

2022-04-03 12:26 UTC, cyberik-dev commented on Task1/ideal_weight.rb
> +      warn "incorrect input"
also, you can raise an exception here

raise AttributeError, 'Parameters must be positive numbers!'
https://rollbar.com/guides/ruby/how-to-raise-exceptions-in-ruby/

and handle it in the call method
```ruby
  def call
    validate_parameters
    area
  rescue AttributeError => e
    warn e
  end

2022-04-04 07:10 UTC, gbGiorgi commented on Task1/ideal_weight.rb
> +class Ideal
i have Replaced the class name according to the file.

2022-04-04 07:11 UTC, gbGiorgi commented on Task1/ideal_weight.rb
> +  NUMBER = 110
I changed both the name of the constant and the name of the class.

2022-04-04 07:12 UTC, gbGiorgi commented on Task1/ideal_weight.rb
> +#ideal weight
I corrected the code according to rubocope notes

2022-04-04 07:13 UTC, gbGiorgi commented on Task1/ideal_weight.rb
> +  def error_message
corrected all names.

2022-04-04 07:13 UTC, gbGiorgi commented on Task1/ideal_weight.rb
> +
added call method and changed other methods to private

2022-04-04 07:15 UTC, gbGiorgi commented on Task1/ideal_weight.rb
> +    if @height.zero?
i have modified method for this error

2022-04-04 07:16 UTC, gbGiorgi commented on Task1/ideal_weight.rb
> +  def weight
corrected all names...

2022-04-04 07:20 UTC, gbGiorgi commented on Task1/ideal_weight.rb
> +      warn "incorrect input"
yes, however in this moment i have fixed all problems and mistakes in my code, tested all possible inputs and It works much better now than ever.

2022-04-05 11:53 UTC, cyberik-dev requested changes

2022-04-05 11:53 UTC, cyberik-dev commented on Task1/ideal_weight.rb
> +puts IdealWeight.new.call
good job but correct rubocop's last remark please

Layout/TrailingEmptyLines: Final newline missing.
puts IdealWeight.new.call

2022-04-05 11:53 UTC, cyberik-dev commented on Task1/ideal_weight.rb
> +    return unless @height.to_i <= EDGE || @height.count('a-zA-Z').positive?
move 'a-zA-Z' to a constant

2022-04-05 11:53 UTC, cyberik-dev commented on Task1/ideal_weight.rb
> +    difference = @height.to_i - SUBSTRACTOR
you can extract this to a method

please read about Ruby Memoization
https://www.honeybadger.io/blog/ruby-rails-memoization/
https://www.justinweiss.com/articles/4-simple-memoization-patterns-in-ruby-and-one-gem/
https://thoughtbot.com/blog/ruby-memoization-and-alternatives

and use it in this method

2022-04-05 11:53 UTC, cyberik-dev commented on Task1/ideal_weight.rb
> +    if difference.negative?
You also can use a predicate method here

`if ideal_weight?`

2022-04-05 12:04 UTC, gbGiorgi commented on Task1/ideal_weight.rb
> +puts IdealWeight.new.call
i did it just now

2022-04-05 12:04 UTC, gbGiorgi commented on Task1/ideal_weight.rb
> +    return unless @height.to_i <= EDGE || @height.count('a-zA-Z').positive?
i have created new constant for it

2022-04-05 12:05 UTC, gbGiorgi commented on Task1/ideal_weight.rb
> +    difference = @height.to_i - SUBSTRACTOR
yes i did it just now

2022-04-05 12:05 UTC, gbGiorgi commented on Task1/ideal_weight.rb
> +    if difference.negative?
ok

2022-04-08 12:21 UTC, merged